project:
  type: website
  output-dir: docs

website:
  title: "ashhssn"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: extra.qmd
        text: Extra Information

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



