project:
  type: website
  output-dir: docs

website:
  title: "ashhssn"
  navbar:
    logo: imgs/logo.jpg
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: extra.qmd
        text: Extra Information

format:
  html:
    theme: minty
    css: styles.css
    toc: true



